### ISSUE TITLE
getFileLocation return invalid URL

### ISSUE THREAD

**Issue by abdox2** [parse-server-modules/parse-server-fs-adapter#1]
the getFileLocation function is missing the applicationId;

function getFileLocation(config, filename) {
      return config.mount + '/files/' + config.applicationId + '/' + encodeURIComponent(filename);
}

please fix it

**Comment by flovilmart** [comment]
Not sure that's the expected behaviour, the original implementation don't have the applicationId
@dtsolis, what do you think?

**Comment by abdox2** [comment]
well. when i want to get the file. parse server send me a error unauthorized. in the default one with mongodb the applicationId is present. that's why i added it, and the file system adapter work afterwards

**Comment by flovilmart** [comment]
so propose a pull request

**Comment by abdox2** [comment]
OK :)

**Comment by abdox2** [comment]
u know im new at this pull request stuff hhhhhhh. i thought is like Issues. how the hell u create one

**Comment by flovilmart** [comment]
http://www.lmgtfy.com/?q=github+how+to+submit+a+pull+request&l=1

**Comment by abdox2** [comment]
that was funny hhhhhhh, well played

**Comment by dtsolis** [comment]
@flovilmart No, the original implementation doesn't include the application id. The adapter, save files under the directory passed on the initialization. Application id shouldn't be relevant to "where" files are saved. 

@abdox2 Is there a chance that you started the server using the GridStoreAdapter before using FileSystemAdapter? If yes, are you trying to get a file that you previously saved using the GridStoreAdapter?

**Comment by flovilmart** [comment]
> Application id shouldn't be relevant to "where" files are saved.
agreed, I don't see why we could not add it, if that don't break backwards compatibility.

**Comment by abdox2** [comment]
yes i was playing with both of them back and forth. to see why parse with FileSystemAdapter return unauthorized?? maybe the application id is ment to be a file key. because u can change it afterwards and change the whole file system urls for security

**Comment by flovilmart** [comment]
If you play with them back and forth, your files can't be properly served. As you save one in GridStore and than ask fs-adpater to retrieve it. You may get an unauthorized error as the files adapter can't handle your file

**Comment by abdox2** [comment]
if i don't add the application id to the FileSystemAdapter. and save the file u get unauthorized but if u add the application id manually in the link like "...files/appid/filename" u get the file

**Comment by dtsolis** [comment]
I'm not sure I can understand what causing this issue. If it's something that the adapter is doing wrong or this is how parse server is designed to work when you switch adapters. I would strongly recommend to make a fresh installation of the parse server, use the fs-adapter and try again.

**Comment by abdox2** [comment]
could u please test the fs-adapter by uploading some file then get there URL and test it afterwards. u gana get the  "error unauthorized" to see my point

**Comment by flovilmart** [comment]
Fixed by #2
