### ISSUE TITLE
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by danielapsmaior** [parse-server-modules/parse-server-fs-adapter#4]
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
bizzkuit@3.0.0 /home/pedro/bizzkuit_parse
└─┬ parse-server-fs-adapter@1.0.0 
  ├─┬ jasmine@2.4.1 
  │ ├── exit@0.1.2 
  │ ├─┬ glob@3.2.11 
  │ │ └─┬ minimatch@0.3.0 
  │ │   ├── lru-cache@2.7.3 
  │ │   └── sigmund@1.0.1 
  │ └── jasmine-core@2.4.1 
  └── parse-server-conformance-tests@1.0.0

**Comment by flovilmart** [comment]
This is a dependency of glob, that is itself a dependency of jasmine...

**Comment by danielapsmaior** [comment]
Thank you. Have found the right issue at: https://github.com/jasmine/jasmine-npm/issues/78
