### ISSUE TITLE
 file adapter usage for other cloud providers with help of pkgcloud node library

### ISSUE THREAD

**Issue by gowridev** [parse-server-modules/parse-server-fs-adapter#9]
@flovilmart : Currently,parse-server-fs-adapter supports amazon and google cloud services. If it use [pkgcloud](https://github.com/pkgcloud/pkgcloud#supported-apis) library as plugin. This functionality will be available more cloud service providers. please share your thoughts on this.

**Comment by flovilmart** [comment]
It seems to be a good candidate for a standalone storage adapter indeed. This particular adapter works anywhere as it just stores the files on the file system
